default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('DB_HOST') %>
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>
  schema_search_path: public

development:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') %>_dev

test:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') %>_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') %>
